title: Rik van den Ende
description: A blog with some tech posts and maybe some pictures

author:
  name: Rik van den Ende
  email: rik.ende@gmail.com

social_links:
  twitter: RikEnde
  github:  RikEnde
  linkedin: rikende

avatar: https://avatars0.githubusercontent.com/u/6178351?s=400

# Build settings
theme: minima

permalink:            pretty

markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
